# Generated by Django 5.2.5 on 2025-08-11 07:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='blog_name',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='blog_description',
        ),
        migrations.AddField(
            model_name='blog',
            name='content',
            field=models.TextField(default=1, verbose_name='Описание'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blog',
            name='blog_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания блога'),
        ),
    ]
