# -*- coding: utf-8 -*-
"""
Django settings for myproject project.

This file contains all the configuration for your Django project.
Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see:
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see:
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Defines the base directory of the project.
# BASE_DIR will point to the project root (django_project).
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production.
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# This key is used for cryptographic signing and should be unique and well-protected.
SECRET_KEY = 'django-insecure-#az46g0ox=4bk0(a^)mr9vjks!k#6wuj0+m9g%e7a83rt+bu&&'

# SECURITY WARNING: don't run with debug turned on in production!
# Debug mode (DEBUG=True) displays detailed error information, which is insecure for a live server.
DEBUG = True

# A list of hosts/domains that are allowed to serve this site.
# Can be left empty in development. For production, you must specify the domain name.
ALLOWED_HOSTS = []


# Application definition
# A list of all applications that Django will use in this project.
INSTALLED_APPS = [
    # Standard Django applications:
    'django.contrib.admin',         # The admin site
    'django.contrib.auth',          # Authentication framework
    'django.contrib.contenttypes',  # Content type framework
    'django.contrib.sessions',      # Session framework
    'django.contrib.messages',      # Messaging framework
    'django.contrib.staticfiles',   # Framework for managing static files (CSS, JS, images)
    
    # This project's applications:
    'blog',                         # Our "blog" application
]

# Middleware
# Classes that process requests and responses globally.
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# Points to the root URL configuration file of the project.
ROOT_URLCONF = 'myproject.urls'

# Template settings
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [], # Directories where Django will look for templates.
        'APP_DIRS': True, # Tells Django to look for templates in 'templates' directories inside applications.
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# Points to the WSGI application used by web servers.
WSGI_APPLICATION = 'myproject.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
# Database connection settings are configured here.
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3', # Using SQLite
        'NAME': BASE_DIR / 'db.sqlite3',       # The database file will be located in the project's root directory.
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators
# Used to check the strength of user passwords.
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us' # Project language code. 'en-us' - English (US), 'ru-ru' - Russian (Russia).

TIME_ZONE = 'UTC' # Project time zone.

USE_I18N = True # Enables Django's translation system.

USE_TZ = True # Enables time zone support.


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/' # URL prefix for static files.

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
