# Generated by Django 5.2.5 on 2025-08-11 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_name', models.CharField(max_length=80, verbose_name='Название блога')),
                ('blog_description', models.CharField(max_length=1000, verbose_name='Описание')),
                ('blog_date', models.DateField(blank=True, null=True, verbose_name='Дата создания блога')),
            ],
            options={
                'verbose_name': ('Блог',),
                'verbose_name_plural': 'Блоги',
            },
        ),
    ]
